// <auto-generated />
using System;
using Maliev.LeaveService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.LeaveService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    [Migration("20251229063211_SyncModelChanges")]
    partial class SyncModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.LeaveService.Domain.Entities.LeaveApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("LeaveRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_request_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_leave_approvals");

                    b.HasIndex("LeaveRequestId")
                        .HasDatabaseName("ix_leave_approvals_leave_request_id");

                    b.ToTable("leave_approvals");
                });

            modelBuilder.Entity("Maliev.LeaveService.Domain.Entities.LeaveBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CarriedForward")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("carried_forward");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("Entitled")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("entitled");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<int>("LeaveType")
                        .HasColumnType("integer")
                        .HasColumnName("leave_type");

                    b.Property<decimal>("Pending")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pending");

                    b.Property<decimal>("Used")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("used");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_leave_balances");

                    b.HasIndex("EmployeeId", "LeaveType", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_leave_balances_employee_id_leave_type_year");

                    b.ToTable("leave_balances");
                });

            modelBuilder.Entity("Maliev.LeaveService.Domain.Entities.LeavePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccrualRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("accrual_rate");

                    b.Property<decimal>("DefaultEntitlement")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("default_entitlement");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LeaveType")
                        .HasColumnType("integer")
                        .HasColumnName("leave_type");

                    b.Property<decimal>("MaxCarryForward")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_carry_forward");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_consecutive_days");

                    b.Property<int>("RequiredApprovalLevels")
                        .HasColumnType("integer")
                        .HasColumnName("required_approval_levels");

                    b.HasKey("Id")
                        .HasName("pk_leave_policies");

                    b.HasIndex("LeaveType")
                        .IsUnique()
                        .HasDatabaseName("ix_leave_policies_leave_type");

                    b.ToTable("leave_policies");
                });

            modelBuilder.Entity("Maliev.LeaveService.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("HalfDayPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("half_day_period");

                    b.Property<int>("LeaveType")
                        .HasColumnType("integer")
                        .HasColumnName("leave_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_days");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_leave_requests");

                    b.ToTable("leave_requests");
                });

            modelBuilder.Entity("Maliev.LeaveService.Domain.Entities.LeaveApproval", b =>
                {
                    b.HasOne("Maliev.LeaveService.Domain.Entities.LeaveRequest", "LeaveRequest")
                        .WithMany("Approvals")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_approvals_leave_requests_leave_request_id");

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("Maliev.LeaveService.Domain.Entities.LeaveRequest", b =>
                {
                    b.Navigation("Approvals");
                });
#pragma warning restore 612, 618
        }
    }
}
